repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
#-   repo: https://github.com/psf/black
#    rev: 22.6.0
#    hooks:
#    -   id: black
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.961
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]
#         exclude: ^testing/resources/
