name: Publish

on: [push]
   branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Build pypi package
          run: |
            python setup.py bdist

        - name: Pytest
          run: |
            python -m pip install --upgrade pip
            pip install twine
            twine upload

